namespace: jass
registry: jassacr.azurecr.io

frontend:
  image: jassacr.azurecr.io/jass-frontend
  tag: latest
  replicas: 1
  port: 3001
  env:
    NEXT_PUBLIC_API_URL: "http://backend:3000"

backend:
  image: jassacr.azurecr.io/jass-backend
  tag: latest
  replicas: 1
  port: 3000
  env:
    DB_HOST: "postgres"
    DB_PORT: "5432"
    DB_USERNAME: "postgres"
    DB_PASSWORD: "pfe2026"
    DB_NAME: "jass_ecommerce"
    NODE_ENV: "production"
    JWT_SECRET: "jass-secret-key-2025"
    PORT: "3000"
    REDIS_HOST: "redis"       
    REDIS_PORT: "6379"        
    AZURE_COMMUNICATION_CONNECTION_STRING: "endpoint=https://jass-communication.europe.communication.azure.com/;accesskey=Kj5G7LxbpYxouR5A03wkHwggVpong16LAsv37XoM1mCVO9bUAZgfJQQJ99CDACULyCpfiLRiAAAAAZCSjeVH"
    AZURE_EMAIL_SENDER: "donotreply@e5f3ec40-76a1-4255-b6e7-8f354fb39cbb.azurecomm.net"

postgres:
  image: postgres
  tag: 15-alpine
  replicas: 1
  port: 5432
  storage: 1Gi
  env:
    POSTGRES_USER: "postgres"
    POSTGRES_PASSWORD: "pfe2026"
    POSTGRES_DB: "jass_ecommerce"

redis:
  image: redis
  tag: 7-alpine
  replicas: 1
  port: 6379

ingress:
  enabled: true
  host: jass.local
  annotations:
    kubernetes.io/ingress.class: nginx