services:

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: pfe2026
      DB_NAME: jass_ecommerce
      NODE_ENV: development
      JWT_SECRET: jass-secret-key-2025
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AZURE_COMMUNICATION_CONNECTION_STRING: "endpoint=https://jass-communication.europe.communication.azure.com/;accesskey=Kj5G7LxbpYxouR5A03wkHwggVpong16LAsv37XoM1mCVO9bUAZgfJQQJ99CDACULyCpfiLRiAAAAAZCSjeVH"
      AZURE_EMAIL_SENDER: "donotreply@e5f3ec40-76a1-4255-b6e7-8f354fb39cbb.azurecomm.net"

  db:
    image: postgres:15-alpine
    container_name: jass_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pfe2026
      POSTGRES_DB: jass_ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jass_ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: jass_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data: