sonar.organization=ghofranepfe2026
sonar.projectKey=ghofrane-benach_JASS---PFE
sonar.projectName=JASS E-Commerce
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**
