sonar.organization=ghofranepfe2026
sonar.projectKey=ghofrane-benach_JASS---PFE
sonar.projectName=JASS E-Commerce
sonar.sources=backend/src,frontend/app,frontend/component,frontend/context,frontend/lib
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/.terraform/**,**/test-results/**,**/playwright-report/**,**/*.zip,**/terraform.tfstate*
sonar.typescript.tsconfigPath=backend/tsconfig.json
